JiffleNowDev/src/objects/JNSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores the JN User Authorization details</description>
    <fields>
        <fullName>JNAdmin_Test_email__c</fullName>
        <description>email id used for system administrator to test jifflenow configuration</description>
        <inlineHelpText>Email id for SFDC Administrator to test jifflenow integration.</inlineHelpText>
        <label>Admin Test eMail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>JNCryptoKey__c</fullName>
        <label>JNCryptoKey</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JNEndpoint_URL__c</fullName>
        <description>JN Endpoint URL</description>
        <inlineHelpText>Enter the JN Endpoint URL</inlineHelpText>
        <label>JNEndpoint_URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JNoAuthEndpoint_URL__c</fullName>
        <description>Used for oAuth authorization url.</description>
        <inlineHelpText>Used for oAuth authorization url.</inlineHelpText>
        <label>JNoAuthEndpoint_URL</label>
        <type>Url</type>
    </fields>
    <label>JNSettings</label>
</CustomObject>

JiffleNowDev/src/classes/JNOauthControllerTest.cls
@isTest
public class JNOauthControllerTest {
    
    
    static testmethod void oauthtest(){
        insert new JNSettings__c(name = 'JNSettings',JNEndpoint_URL__c='https://tugboat-testing.jifflenow.com/api',JNoAuthEndpoint_URL__c='https://tugboat-testing.jifflenow.com/api/oauth',JNCryptoKey__c='bWbuwlbfhp9Ptlc3yz9ivJCGfIJs1cdkvREA1Mq6qlU=',JNAdmin_Test_email__c='demo@demo.com');
        Test.startTest();
        //Creating object for JNOauthControoller
        JNOauthController jnOauth=new JNOauthController();
        
        
        System.currentPageReference().getParameters().put('code', 'testcode');
        System.currentPageReference().getParameters().put('error', 'testcode');
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        jnOauth.checkTokenRequest();
        
        jnOauth.getAccessToken(false);
        jnOauth.getAccessToken(true); 
        
        jnOauth.initAuth();
        jnOauth.jnSettings.JNEndpoint_URL__c='goggle';
        jnOauth.initAuth();
        
        jnOauth.doCancel();
        jnOauth.chgToedit();
        jnOauth.getEmailId();
        jnOauth.getEndURL();
        
        
    }
}