JiffleNowDev/src/objects/Mapping__c.object
<CustomObject>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mapping_UUID__c</fullName>
        <externalId>true</externalId>
        <label>Mapping UUID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <label>Object API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Label__c</fullName>
        <label>Object Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Mapping</label>
    <nameField>
        <displayFormat>MN-{0000}</displayFormat>
        <label>Mapping Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JiffleNowDev/src/classes/JNMappingListTest.cls
@isTest(seeAllData=true)
private class JNMappingListTest {
	static testMethod void myUnitTest(){
		Test.setMock(HttpCalloutMock.class, new MockResposeHttp());
		Mapping__c mobj = new Mapping__c();
		mobj.Enabled__c = true;
		mobj.Unique_Key__c = 'bfb6cf90-2daa-4d4c-8c40-da89af53b81d';
		insert mobj;
		Test.startTest();
		JNMappingList jn = new JNMappingList();
		Pagereference pg = Page.JNMappingList;
		Test.setCurrentPage(pg);
		
		jn.EnableId = mobj.Id;
		jn.JNSend();
		System.debug('FROMTESTCLASS '+mobj);
		jn.Initialload();
		jn.getMappings();
		jn.refresh();
		jn.next();
		jn.first();
		jn.previous();
		jn.last();
		jn.Redirect();
		list<Mapping__c> Mlist = new list<Mapping__c>();
		Mlist = [Select Name, Enabled__c, Field_API_Name__c, Field_Label__c, Field_Type__c,Mapping_UUID__c,Object_API_Name__c,Object_Label__c,Unique_Key__c from Mapping__c order by Object_Label__c]; 
		System.assertEquals(true, Mlist.size()>0);   
		Test.stopTest();
	}
}